# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://travis-ci.org/
sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "11"
  - "12"
cache:
  directories:
  - node_modules
before_install:
install:
  - npm install
branches:
  only:
  - master
script:
  # 自动化测试
  npm run test